# Generated by Django 5.1.15 on 2026-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
