# Generated by Django 5.1.15 on 2026-02-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("student_name", "trip"), name="unique_student_per_trip"
            ),
        ),
    ]
