# Generated by Django 5.1.15 on 2026-02-20 16:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_unique_student_per_trip"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registration",
            name="unique_student_per_trip",
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("student_name"),
                models.F("trip"),
                name="unique_student_per_trip",
            ),
        ),
    ]
